---
title: "Visualizing Non-Overlapping Disadvantaged Census Tracts: Bolstering CalEnviroScreen Considerations"
author: "Sofia Ingersoll"
format:
  html:
    code-fold: true
    code-summary: "View the code"
embedded-sources: true
output:
  html_document:
    print_df: paged
    toc: yes
    toc_depth: 4
    toc_float: yes
---

```{r set-up, message = FALSE}
library(sf)
#library(sp)
library(tmap)
library(here)
library(stars)
library(terra)
library(raster)
library(maptiles)
library(tidyverse)
library(leaflet)
#library(sfheaders)
#library(ggspatial)
library(tmaptools)
library(osmextract) 
library(RColorBrewer)
```


# Read CalEnviroScreen Data
```{r read_n_wrangle_calenviro}
calenviro <- st_read(here("data","CalEnviroScreen","CES4 Final Shapefile.shp")) %>% 
  janitor::clean_names() %>% 
  st_make_valid()

# housing burden is a good parameter to visualize
# let's get an idea of the bin distribution for plotting
range(calenviro$hous_burd)

# remove the -999.0, that's an NA
calenviro <- calenviro %>% 
  filter(hous_burd != -999.0)

# check! nice!
range(calenviro$hous_burd)

calenviro <- st_transform(calenviro,
                          4326) %>% 
  st_make_valid()
```


# Read CDC EJ Data
This raw data only contains CA observations, so no need to filter. However, it lacks geo-info, so we're going to relate the df using `calenviro$tract` and `cdc_ej$fips`

```{r read_n_wrangle_cdc_ej}
cdc_ej <- read_csv(here("data", "CDC_Index", "California_EJ.csv"),
                    show_col_types = FALSE) %>% 
  janitor::clean_names() %>% 
  # match dtype w/ calenviro
  mutate(geoid = as.double(geoid))

#head(cdc_ej , 3)   
  
# now cdc_svi contains geo-info and all the calenviro info
cdc_ej_geo <- left_join(cdc_ej, calenviro, by = c("geoid" = "tract"))
                    
head(cdc_ej_geo , 3)     

# let's make it a spatial object for mapping now
cdc_ej_geo <- st_as_sf(cdc_ej_geo) %>% 
  st_transform(crs = 4326) %>% 
  st_make_valid()

# fix geometries
cdc_ej_geo <- cdc_ej_geo[!st_is_empty(cdc_ej_geo), ]
```

```{r cdc_ej_map}
# we'll break housing burden into quantiles
bins <- seq(0, 100, by = 25)

# i want a map will all the data layered for for selection against calenviro
tmap_mode(mode = "view")

tm_shape(calenviro) +
  
  tm_basemap(leaflet::providers$OpenStreetMap) +
  
  tm_polygons(col = 'hous_burd',
              palette = 'plasma',
              style = 'fixed',
              breaks = bins) +
  
  tm_shape(cdc_ej_geo) +
  
  # areas with overlap are made to be white,
  # as to "white out" areas not of interest  
  # the only visible regions are where the data do no overlap 
  tm_bubbles(size = .1,
             alpha = 0.5,
             palette = "plasma",
             border.col = 'white'
             ) 
```